language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

sudo: false

before_install:
    # Prevent "Please tell me who you are" errors for certain DZIL configs
    - git config --global user.name "TravisCI"
    - |
      if perl -e 'if ($] < "5.008009") { exit(0) } else { exit(1) }'; then
        perlbrew --notest install perl-5.8.9
        perlbrew use perl-5.8.9
        perl --version
      fi

install:
    # Deal with all of the DZIL dependancies, quickly and quietly
    # 6.0 and later doesn't run on Perls older than 5.14
    - cpanm --quiet --notest --skip-satisfied Dist::Zilla~'>=5.04, <6.000'
    - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
    - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
    - dzil listdeps | grep -vP '[^\w:]' | cpanm --verbose --skip-satisfied --notest

script:
   - dzil smoke --release --author
